import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Generic Concrete Table",
    image: "http://placeimg.com/640/480/business",
    price: "84.00",
    categoryName: "Black Widow",
    productType: "Costumes",
    inStock: true,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Handmade Fresh Chicken",
    image: "http://placeimg.com/640/480/transport",
    price: "512.00",
    categoryName: "Black Widow",
    productType: "Bags",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 4, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Refined Fresh Ball",
    image: "http://placeimg.com/640/480/nightlife",
    price: "457.00",
    categoryName: "Hulk",
    productType: "Bags",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 4, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Handmade Metal Computer",
    image: "http://placeimg.com/640/480/city",
    price: "512.00",
    categoryName: "Hulk",
    productType: "T-Shirts & Tops",
    inStock: true,
    fastDelivery: false,
    rating: { starRating: 2, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Refined Granite Chair",
    image: "http://placeimg.com/640/480/people",
    price: "553.00",
    categoryName: "Captain America",
    productType: "Action Figures",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 1, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Incredible Concrete Hat",
    image: "http://placeimg.com/640/480/cats",
    price: "450.00",
    categoryName: "Black Widow",
    productType: "Bags",
    inStock: true,
    fastDelivery: false,
    rating: { starRating: 4, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Licensed Frozen Bike",
    image: "http://placeimg.com/640/480/fashion",
    price: "57.00",
    categoryName: "Black Widow",
    productType: "Action Figures",
    inStock: true,
    fastDelivery: false,
    rating: { starRating: 5, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Gorgeous Steel Salad",
    image: "http://placeimg.com/640/480/fashion",
    price: "585.00",
    categoryName: "Thor",
    productType: "Bags",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 2.5, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Fantastic Granite Sausages",
    image: "http://placeimg.com/640/480/sports",
    price: "842.00",
    categoryName: "Captain America",
    productType: "Costumes",
    inStock: true,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Sleek Rubber Sausages",
    image: "http://placeimg.com/640/480/animals",
    price: "304.00",
    categoryName: "Hulk",
    productType: "Bags",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Generic Granite Gloves",
    image: "http://placeimg.com/640/480/nightlife",
    price: "492.00",
    categoryName: "Ironman",
    productType: "T-Shirts & Tops",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Sleek Plastic Gloves",
    image: "http://placeimg.com/640/480/sports",
    price: "100.00",
    categoryName: "Hulk",
    productType: "Costumes",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Generic Plastic Shirt",
    image: "http://placeimg.com/640/480/people",
    price: "745.00",
    categoryName: "Ironman",
    productType: "Bags",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Fantastic Frozen Chips",
    image: "http://placeimg.com/640/480/food",
    price: "676.00",
    categoryName: "Thor",
    productType: "Costumes",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Tasty Rubber Ball",
    image: "http://placeimg.com/640/480/people",
    price: "247.00",
    categoryName: "Ironman",
    productType: "Action Figures",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Sleek Fresh Hat",
    image: "http://placeimg.com/640/480/fashion",
    price: "580.00",
    categoryName: "Thor",
    productType: "T-Shirts & Tops",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Sleek Cotton Pizza",
    image: "http://placeimg.com/640/480/cats",
    price: "720.00",
    categoryName: "Captain America",
    productType: "Costumes",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Ergonomic Soft Hat",
    image: "http://placeimg.com/640/480/sports",
    price: "445.00",
    categoryName: "Ironman",
    productType: "Action Figures",
    inStock: true,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Fantastic Concrete Cheese",
    image: "http://placeimg.com/640/480/city",
    price: "743.00",
    categoryName: "Ironman",
    productType: "Action Figures",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Rustic Rubber Cheese",
    image: "http://placeimg.com/640/480/business",
    price: "470.00",
    categoryName: "Captain America",
    productType: "T-Shirts & Tops",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Small Frozen Chair",
    image: "http://placeimg.com/640/480/animals",
    price: "473.00",
    categoryName: "Hulk",
    productType: "T-Shirts & Tops",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Handcrafted Steel Keyboard",
    image: "http://placeimg.com/640/480/nature",
    price: "911.00",
    categoryName: "Thor",
    productType: "Bags",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Fantastic Soft Soap",
    image: "http://placeimg.com/640/480/business",
    price: "332.00",
    categoryName: "Captain America",
    productType: "Action Figures",
    inStock: true,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Awesome Soft Towels",
    image: "http://placeimg.com/640/480/business",
    price: "185.00",
    categoryName: "Ironman",
    productType: "Action Figures",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Rustic Rubber Towels",
    image: "http://placeimg.com/640/480/food",
    price: "240.00",
    categoryName: "Thor",
    productType: "T-Shirts & Tops",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Ergonomic Granite Fish",
    image: "http://placeimg.com/640/480/nightlife",
    price: "892.00",
    categoryName: "Hulk",
    productType: "T-Shirts & Tops",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Unbranded Soft Pants",
    image: "http://placeimg.com/640/480/nightlife",
    price: "322.00",
    categoryName: "Thor",
    productType: "Action Figures",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Practical Rubber Pizza",
    image: "http://placeimg.com/640/480/nature",
    price: "23.00",
    categoryName: "Hulk",
    productType: "Action Figures",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Sleek Granite Keyboard",
    image: "http://placeimg.com/640/480/people",
    price: "939.00",
    categoryName: "Black Widow",
    productType: "T-Shirts & Tops",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Unbranded Cotton Towels",
    image: "http://placeimg.com/640/480/people",
    price: "553.00",
    categoryName: "Hulk",
    productType: "Bags",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Handmade Soft Shoes",
    image: "http://placeimg.com/640/480/technics",
    price: "246.00",
    categoryName: "Black Widow",
    productType: "Bags",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Tasty Rubber Fish",
    image: "http://placeimg.com/640/480/nightlife",
    price: "857.00",
    categoryName: "Hulk",
    productType: "Bags",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Licensed Wooden Hat",
    image: "http://placeimg.com/640/480/business",
    price: "434.00",
    categoryName: "Ironman",
    productType: "Bags",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Handcrafted Concrete Tuna",
    image: "http://placeimg.com/640/480/fashion",
    price: "665.00",
    categoryName: "Hulk",
    productType: "Action Figures",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Practical Granite Ball",
    image: "http://placeimg.com/640/480/nature",
    price: "540.00",
    categoryName: "Ironman",
    productType: "T-Shirts & Tops",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Sleek Cotton Keyboard",
    image: "http://placeimg.com/640/480/cats",
    price: "273.00",
    categoryName: "Hulk",
    productType: "Bags",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Tasty Concrete Pants",
    image: "http://placeimg.com/640/480/technics",
    price: "825.00",
    categoryName: "Thor",
    productType: "Action Figures",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Handcrafted Granite Soap",
    image: "http://placeimg.com/640/480/city",
    price: "354.00",
    categoryName: "Captain America",
    productType: "Bags",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Handmade Steel Table",
    image: "http://placeimg.com/640/480/nightlife",
    price: "575.00",
    categoryName: "Ironman",
    productType: "Bags",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Small Concrete Chips",
    image: "http://placeimg.com/640/480/business",
    price: "14.00",
    categoryName: "Captain America",
    productType: "Costumes",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Refined Rubber Pizza",
    image: "http://placeimg.com/640/480/food",
    price: "556.00",
    categoryName: "Hulk",
    productType: "Costumes",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Incredible Plastic Mouse",
    image: "http://placeimg.com/640/480/cats",
    price: "379.00",
    categoryName: "Hulk",
    productType: "Costumes",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Unbranded Cotton Chicken",
    image: "http://placeimg.com/640/480/abstract",
    price: "192.00",
    categoryName: "Thor",
    productType: "T-Shirts & Tops",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Gorgeous Granite Gloves",
    image: "http://placeimg.com/640/480/food",
    price: "187.00",
    categoryName: "Captain America",
    productType: "T-Shirts & Tops",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Licensed Soft Tuna",
    image: "http://placeimg.com/640/480/nature",
    price: "997.00",
    categoryName: "Hulk",
    productType: "Action Figures",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Refined Soft Pants",
    image: "http://placeimg.com/640/480/food",
    price: "900.00",
    categoryName: "Black Widow",
    productType: "Costumes",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Generic Steel Table",
    image: "http://placeimg.com/640/480/city",
    price: "386.00",
    categoryName: "Hulk",
    productType: "Costumes",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Handcrafted Metal Towels",
    image: "http://placeimg.com/640/480/nightlife",
    price: "10.00",
    categoryName: "Captain America",
    productType: "Action Figures",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Sleek Cotton Shoes",
    image: "http://placeimg.com/640/480/technics",
    price: "644.00",
    categoryName: "Ironman",
    productType: "T-Shirts & Tops",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
  {
    _id: uuid(),
    title: "Fantastic Plastic Gloves",
    image: "http://placeimg.com/640/480/technics",
    price: "703.00",
    categoryName: "Thor",
    productType: "Costumes",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30
  },
];
