import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Black Widow Stingers Play Set",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314729/marvel-kart/widow/widow_cos_1.webp",
    price: "844.00",
    categoryName: "Black Widow",
    productType: "Costumes",
    inStock: true,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Black Widow Avenger Spray Paint Tote Bag",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314728/marvel-kart/widow/widow_bag_2.webp",
    price: "512.00",
    categoryName: "Black Widow",
    productType: "Bags",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 4, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Thor: Ragnarok Ready for Battle Allover Print Tote",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314730/marvel-kart/hulk/hulk_bag_1.webp",
    price: "457.00",
    categoryName: "Hulk",
    productType: "Bags",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 4, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Hulk Tee for Kids",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314730/marvel-kart/hulk/hulk_t_1.webp",
    price: "512.00",
    categoryName: "Hulk",
    productType: "T-Shirts & Tops",
    inStock: true,
    fastDelivery: false,
    rating: { starRating: 2, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Black Widow Target Tote Bag",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314728/marvel-kart/widow/widow_bag_3.webp",
    price: "450.00",
    categoryName: "Black Widow",
    productType: "Bags",
    inStock: true,
    fastDelivery: false,
    rating: { starRating: 4, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Black Widow and Yelena Bobble-Head Figure Set",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314728/marvel-kart/widow/widow_fig_1.webp",
    price: "948.00",
    categoryName: "Black Widow",
    productType: "Action Figures",
    inStock: true,
    fastDelivery: false,
    rating: { starRating: 5, totalRating: 20 },
    offer: 30,
  },

  {
    _id: uuid(),
    title: "Iron Man Long Sleeve Tee",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314730/marvel-kart/ironman/ironman_t_1.webp",
    price: "492.00",
    categoryName: "Ironman",
    productType: "T-Shirts & Tops",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Iron Man Costume for Kids",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314730/marvel-kart/ironman/ironman_cos_1.webp",
    price: "745.00",
    categoryName: "Ironman",
    productType: "Costumes",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },

  {
    _id: uuid(),
    title: "Iron Man Invincible Pewter Figurine",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314729/marvel-kart/ironman/ironman_fig_4.webp",
    price: "247.00",
    categoryName: "Ironman",
    productType: "Action Figures",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Thor T-Shirt for Adults",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314729/marvel-kart/thor/thor_t_1.webp",
    price: "580.00",
    categoryName: "Thor",
    productType: "T-Shirts & Tops",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Captain America Costume for Kids",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314731/marvel-kart/captain/captain_cos_1.webp",
    price: "720.00",
    categoryName: "Captain America",
    productType: "Costumes",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Iron Man Talking Action Figure",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314730/marvel-kart/ironman/ironman_fig_3.webp",
    price: "445.00",
    categoryName: "Ironman",
    productType: "Action Figures",
    inStock: true,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "LEGO Iron Man Figure 76206 – The Infinity Saga",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314730/marvel-kart/ironman/ironman_fig_2.webp",
    price: "743.00",
    categoryName: "Ironman",
    productType: "Action Figures",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Captain America Retro Tee",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314731/marvel-kart/captain/captain_t_2.webp",
    price: "470.00",
    categoryName: "Captain America",
    productType: "T-Shirts & Tops",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Hulk Champion of Sakaar Graphic T-Shirt",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314732/marvel-kart/hulk/hulk_t_2.webp",
    price: "473.00",
    categoryName: "Hulk",
    productType: "T-Shirts & Tops",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Civil Warrior Action Figure",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314731/marvel-kart/captain/captain_fig_1.webp",
    price: "332.00",
    categoryName: "Captain America",
    productType: "Action Figures",
    inStock: true,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Iron Man Pewter Figurine– Limited Edition",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314730/marvel-kart/ironman/ironman_fig_1.webp",
    price: "540.00",
    categoryName: "Ironman",
    productType: "Action Figures",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Thor Blue Lightning Graphic T-Shirt",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314729/marvel-kart/thor/thor_t_2.webp",
    price: "440.00",
    categoryName: "Thor",
    productType: "T-Shirts & Tops",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Thor God of Thunder Pewter Figurine",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314729/marvel-kart/thor/thor_fig_1.webp",
    price: "322.00",
    categoryName: "Thor",
    productType: "Action Figures",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Black Widow Hourglass T-Shirt",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314728/marvel-kart/widow/widow_t_2.webp",
    price: "939.00",
    categoryName: "Black Widow",
    productType: "T-Shirts & Tops",
    inStock: true,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "UHulk Roar Tote Bag",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314732/marvel-kart/hulk/hulk_bag_2.webp",
    price: "553.00",
    categoryName: "Hulk",
    productType: "Bags",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Black Widow Secret Tote Bag",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314729/marvel-kart/widow/widow_bag_1.webp",
    price: "246.00",
    categoryName: "Black Widow",
    productType: "Bags",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Iron Man ''More than a Suit'' Bag",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314730/marvel-kart/ironman/ironman_bag_1.webp",
    price: "434.00",
    categoryName: "Ironman",
    productType: "Bags",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Hulk Pewter Mini Figurine",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314730/marvel-kart/hulk/hulk_fig_1.webp",
    price: "665.00",
    categoryName: "Hulk",
    productType: "Action Figures",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Iron Man ''More than a Suit'' T-Shirt",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314730/marvel-kart/ironman/ironman_t_3.webp",
    price: "540.00",
    categoryName: "Ironman",
    productType: "T-Shirts & Tops",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Thor Pewter Mini Figurine",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314729/marvel-kart/thor/thor_fig_2.webp",
    price: "825.00",
    categoryName: "Thor",
    productType: "Action Figures",
    inStock: false,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Captain America Backpack",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314732/marvel-kart/captain/captain_bag_1.webp",
    price: "449.00",
    categoryName: "Captain America",
    productType: "Bags",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Captain America ''This Dad Is Legendary'' T-Shirt",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314731/marvel-kart/captain/captain_t_1.webp",
    price: "187.00",
    categoryName: "Captain America",
    productType: "T-Shirts & Tops",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Black Widow T-Shirt – Future Fight",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314728/marvel-kart/widow/widow_t_1.webp",
    price: "900.00",
    categoryName: "Black Widow",
    productType: "T-Shirts & Tops",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },

  {
    _id: uuid(),
    title: "Captain America Pewter Figurine",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314732/marvel-kart/captain/captain_fig_2.webp",
    price: "704.00",
    categoryName: "Captain America",
    productType: "Action Figures",
    inStock: false,
    fastDelivery: false,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
  {
    _id: uuid(),
    title: "Iron Man Tee for Adults",
    image:
      "https://res.cloudinary.com/dxhz9n8hc/image/upload/v1649314730/marvel-kart/ironman/ironman_t_2.webp",
    price: "644.00",
    categoryName: "Ironman",
    productType: "T-Shirts & Tops",
    inStock: true,
    fastDelivery: true,
    rating: { starRating: 3, totalRating: 20 },
    offer: 30,
  },
];
