export const ACTION_TYPE = {
  CATEGORIES: "CATEGORIES",
  PRODUCTS: "PRODUCTS",
  PRODUCT_TYPE: "PRODUCT_TYPE",
  SORT_BY: "SORT_BY",
  RATING: "RATING",
  PRICE_RANGE: "PRICE_RANGE",
  STOCK: "STOCK",
  FAST_DELIVERY: "FAST_DELIVERY",
  CLEAR: "CLEAR",
};

export const HIGH_LOW_PRICE = "HIGH_LOW_PRICE";
export const HIGH_LOW_RATING = "HIGH_LOW_RATING";
export const LOW_HIGH_PRICE = "LOW_HIGH_PRICE";
export const LOW_HIGH_RATING = "LOW_HIGH_RATING";
